
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TD = 95;
  public static final int NOSCRIPT = 71;
  public static final int BGSOUND = 12;
  public static final int H6 = 44;
  public static final int GT = 108;
  public static final int H5 = 43;
  public static final int H4 = 42;
  public static final int H3 = 41;
  public static final int H2 = 40;
  public static final int FRAME = 36;
  public static final int H1 = 39;
  public static final int STYLE = 90;
  public static final int LISTING = 61;
  public static final int COLGROUP = 23;
  public static final int PARAM = 77;
  public static final int DFN = 26;
  public static final int TABLE = 93;
  public static final int WBR = 105;
  public static final int SL = 110;
  public static final int KEYGEN = 55;
  public static final int SUP = 92;
  public static final int title = 114;
  public static final int APPLET = 6;
  public static final int BLINK = 14;
  public static final int href = 112;
  public static final int SAMP = 81;
  public static final int ACRONYM = 4;
  public static final int profile = 115;
  public static final int LT = 109;
  public static final int SUB = 91;
  public static final int FONT = 34;
  public static final int TFOOT = 97;
  public static final int FRAMESET = 37;
  public static final int DEL = 25;
  public static final int LI = 59;
  public static final int version = 111;
  public static final int CENTER = 19;
  public static final int ILAYER = 49;
  public static final int OBJECT = 72;
  public static final int XMP = 107;
  public static final int VAR = 106;
  public static final int ADDRESS = 5;
  public static final int HTML = 46;
  public static final int EQ = 117;
  public static final int EMBED = 32;
  public static final int ISINDEX = 53;
  public static final int EM = 31;
  public static final int IFRAME = 48;
  public static final int STRIKE = 88;
  public static final int MULTICOL = 66;
  public static final int BASEFONT = 10;
  public static final int NOBR = 68;
  public static final int SELECT = 82;
  public static final int TEXTAREA = 96;
  public static final int CITE = 20;
  public static final int BDO = 11;
  public static final int ABBR = 3;
  public static final int NOFRAMES = 70;
  public static final int LEGEND = 58;
  public static final int style = 116;
  public static final int DT = 30;
  public static final int INPUT = 51;
  public static final int U = 103;
  public static final int S = 80;
  public static final int DIV = 28;
  public static final int DL = 29;
  public static final int Q = 79;
  public static final int KBD = 54;
  public static final int P = 76;
  public static final int AREA = 7;
  public static final int DIR = 27;
  public static final int NEXTID = 67;
  public static final int DOCTYPE = 113;
  public static final int SMALL = 85;
  public static final int DD = 24;
  public static final int INS = 52;
  public static final int MAP = 62;
  public static final int I = 47;
  public static final int FORM = 35;
  public static final int LINK = 60;
  public static final int EOF = 0;
  public static final int B = 8;
  public static final int A = 2;
  public static final int COL = 22;
  public static final int BLOCKQUOTE = 15;
  public static final int FIELDSET = 33;
  public static final int SPAN = 87;
  public static final int LABEL = 56;
  public static final int BIG = 13;
  public static final int STRONG = 89;
  public static final int SCRIPT = 84;
  public static final int SERVER = 83;
  public static final int TITLE = 100;
  public static final int BODY = 16;
  public static final int MENU = 64;
  public static final int error = 1;
  public static final int OPTGROUP = 74;
  public static final int OL = 73;
  public static final int NOEMBED = 69;
  public static final int UL = 104;
  public static final int SPACER = 86;
  public static final int HEAD = 38;
  public static final int CAPTION = 18;
  public static final int PRE = 78;
  public static final int IMG = 50;
  public static final int BASE = 9;
  public static final int BR = 17;
  public static final int META = 65;
  public static final int CODE = 21;
  public static final int MARQUEE = 63;
  public static final int HR = 45;
  public static final int OPTION = 75;
  public static final int TBODY = 94;
  public static final int TT = 102;
  public static final int TR = 101;
  public static final int LAYER = 57;
  public static final int THEAD = 99;
  public static final int TH = 98;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "A",
  "ABBR",
  "ACRONYM",
  "ADDRESS",
  "APPLET",
  "AREA",
  "B",
  "BASE",
  "BASEFONT",
  "BDO",
  "BGSOUND",
  "BIG",
  "BLINK",
  "BLOCKQUOTE",
  "BODY",
  "BR",
  "CAPTION",
  "CENTER",
  "CITE",
  "CODE",
  "COL",
  "COLGROUP",
  "DD",
  "DEL",
  "DFN",
  "DIR",
  "DIV",
  "DL",
  "DT",
  "EM",
  "EMBED",
  "FIELDSET",
  "FONT",
  "FORM",
  "FRAME",
  "FRAMESET",
  "HEAD",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "HR",
  "HTML",
  "I",
  "IFRAME",
  "ILAYER",
  "IMG",
  "INPUT",
  "INS",
  "ISINDEX",
  "KBD",
  "KEYGEN",
  "LABEL",
  "LAYER",
  "LEGEND",
  "LI",
  "LINK",
  "LISTING",
  "MAP",
  "MARQUEE",
  "MENU",
  "META",
  "MULTICOL",
  "NEXTID",
  "NOBR",
  "NOEMBED",
  "NOFRAMES",
  "NOSCRIPT",
  "OBJECT",
  "OL",
  "OPTGROUP",
  "OPTION",
  "P",
  "PARAM",
  "PRE",
  "Q",
  "S",
  "SAMP",
  "SELECT",
  "SERVER",
  "SCRIPT",
  "SMALL",
  "SPACER",
  "SPAN",
  "STRIKE",
  "STRONG",
  "STYLE",
  "SUB",
  "SUP",
  "TABLE",
  "TBODY",
  "TD",
  "TEXTAREA",
  "TFOOT",
  "TH",
  "THEAD",
  "TITLE",
  "TR",
  "TT",
  "U",
  "UL",
  "WBR",
  "VAR",
  "XMP",
  "GT",
  "LT",
  "SL",
  "version",
  "href",
  "DOCTYPE",
  "title",
  "profile",
  "style",
  "EQ"
  };
}

